### ISSUE TITLE
[ec2] Invalid action DescribeManagedPrefixList

### ISSUE THREAD

**Issue by asangeethada** [darkbitio/aws-recon#138]
I ran the following command **aws_recon -v -q -l -s EC2 -f custom** 

and I get the following error 

/Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.121.1/lib/seahorse/client/plugins/raise_response_errors.rb:17:in `call': The action DescribeManagedPrefixLists is not valid for this web service. (Aws::EC2::Errors::InvalidAction)  

Is this an aws cli issue or an issue with how aws_recon sends the request? 

Thanks

**Comment by joshlarsen** [comment]
Is this happening in `ap-northeast-3` by chance?

**Comment by asangeethada** [comment]
Yes it is.

If i remove the -q flag, it should still collect information about the ec2 instances right ? 

Thanks

**Comment by joshlarsen** [comment]
Upgrade to the latest version, which will gracefully skip that API call in that region.
