### ISSUE TITLE
leverage AWS Cloud Control API

### ISSUE THREAD

**Issue by PatMyron** [darkbitio/aws-recon#149]
`ListResource` from https://aws.amazon.com/blogs/aws/announcing-aws-cloud-control-api/ seems like an easier way to increase type coverage

**Comment by joshlarsen** [comment]
@PatMyron currently there are a lot of services not supported by Cloud Control.

**Comment by PatMyron** [comment]
Aware Cloud Control support is currently limited, but still a useful expansion for the services that are supported by Cloud Control

**Comment by joshlarsen** [comment]
@PatMyron do you have any examples of resources you think Control Control would help collect?

In my experience, the resources that are supported, return very limited details compared to calling the service APIs directly.


S3 Bucket:
```json
{
  "TypeName": "AWS::S3::Bucket",
  "ResourceDescription": {
    "Identifier": "acme-audit-resources",
    "Properties": "{\"BucketName\":\"acme-audit-resources\",\"RegionalDomainName\":\"acme-audit-resources.s3.us-east-2.amazonaws.com\",\"DomainName\":\"acme-audit-resources.s3.amazonaws.com\",\"WebsiteURL\":\"http://acme-audit-resources.s3-website.us-east-2.amazonaws.com\",\"DualStackDomainName\":\"acme-audit-resources.s3.dualstack.us-east-2.amazonaws.com\",\"VersioningConfiguration\":{\"Status\":\"Enabled\"},\"Arn\":\"arn:aws:s3:::acme-audit-resources\"}"
  }
}
```

ECS Cluster:

```json
{
  "TypeName": "AWS::ECS::Cluster",
  "ResourceDescription": {
    "Identifier": "app-server-aae4ee26e088",
    "Properties": "{\"ClusterSettings\":[{\"Value\":\"disabled\",\"Name\":\"containerInsights\"}],\"DefaultCapacityProviderStrategy\":[],\"CapacityProviders\":[\"FARGATE\"],\"ClusterName\":\"app-server-aae4ee26e088\",\"Arn\":\"arn:aws:ecs:us-east-2:123456789012:cluster/app-server-aae4ee26e088\",\"Tags\":[]}"
  }
}
```

In my discussions with some folks at AWS, Cloud Control is aimed at making life easier for infrastructure automation tools. Lifecycle management of resources is the main driver, not necessarily inventory collection/management.
