### ISSUE TITLE
Aws::S3::Errors::MethodNotAllowed in aws-sdk-core

### ISSUE THREAD

**Issue by arafay993** [darkbitio/aws-recon#161]
I am getting this error when running S3 collector:
**the specified method is not allowed against this resource** when calling `get_bucket_accelerate_configuration `. 

Command:
`./aws_recon --regions us-west-2,global --services s3,rds,athena,dynamodb,redshift,elasticache,efs,secretsmanager,cloudfront --output tmp/452036446_aws_recon_output.jsonl --format aws --json-lines`

I tried to find the cause of this error and found this [documentation](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Client.html):

> If you have the correct permissions, but you're not using an identity that belongs to the bucket owner's account, Amazon S3 returns a 405 Method Not Allowed error

But not sure how can I resolve this. Any help would be appreciated.

**Comment by joshlarsen** [comment]
@arafay993 AWS Recon doesn't call `get_bucket_accelerate_configuration`. Are you trying to add this functionality? If so, you can suppress the `MethodNotAllowed` error, by adding `MethodNotAllowed` to the array [here](https://github.com/darkbitio/aws-recon/blob/8c02f7f6aae50699ff97591d2d8296d18b4b210f/lib/aws_recon/collectors/s3.rb#L90).

**Comment by arafay993** [comment]
@joshlarsen, Yeah! actually, I added it by myself. I agree, that it should be suppressed, but is there no solution to avoid it in the first place?

**Comment by joshlarsen** [comment]
@arafay993 not sure, I haven't used that api method before.
